debug

diff --git a/FL_client/docker/Dockerfile b/FL_client/docker/Dockerfile
--- a/FL_client/docker/Dockerfile
+++ b/FL_client/docker/Dockerfile
@@ -1,7 +1,48 @@
-# Use an official Python runtime as a parent image
+## Use an official Python runtime as a parent image
+#FROM python:3.9-slim
+#
+#ENV PYTHONUNBUFFERED 1
+#
+## Set the working directory in the container
+#WORKDIR /app
+#
+## Copy the source code
+#COPY FL_client/src/ /app/src
+#
+## Set the working directory to /app/src/
+#WORKDIR /app/src
+#
+### Update package
+##RUN apt update
+##RUN apt install nano
+##RUN apt install -y pkg-config
+##RUN apt install -y libhdf5-dev
+#
+## Update package lists and install necessary build tools and dependencies
+#RUN apt-get update && apt-get install -y \
+#    nano \
+#    pkg-config \
+#    libhdf5-dev \
+#    gcc \
+#    && rm -rf /var/lib/apt/lists/*
+#
+## Install Python dependencies
+#RUN pip install --no-cache-dir -r requirements.txt
+#
+## Change working directory back to /app/
+#WORKDIR /app
+#
+##ENTRYPOINT ["python", "fl.kmeans.py"]
+##ENTRYPOINT ["python", "rf.py"]
+#CMD ["tail", "-f", "/dev/null"]
+
+####################################(With GPU)############################################################
+
+#FROM nvcr.io/nvidia/l4t-cuda:12.2.12-devel
+FROM nvcr.io/nvidia/l4t-ml:r32.7.1-py3
 FROM python:3.9-slim
 
-ENV PYTHONUNBUFFERED 1
+ENV PYTHONUNBUFFERED=1
 
 # Set the working directory in the container
 WORKDIR /app
@@ -12,26 +53,21 @@ COPY FL_client/src/ /app/src
 # Set the working directory to /app/src/
 WORKDIR /app/src
 
-## Update package
-#RUN apt update
-#RUN apt install nano
-#RUN apt install -y pkg-config
-#RUN apt install -y libhdf5-dev
-
-# Update package lists and install necessary build tools and dependencies
+# Install necessary packages and pip
 RUN apt-get update && apt-get install -y \
     nano \
     pkg-config \
     libhdf5-dev \
     gcc \
+    #python3-pip \
     && rm -rf /var/lib/apt/lists/*
 
 # Install Python dependencies
+#RUN pip3 install --no-cache-dir -r requirements.txt || { echo 'installation failed'; exit 1; }
 RUN pip install --no-cache-dir -r requirements.txt
 
 # Change working directory back to /app/
 WORKDIR /app
 
-#ENTRYPOINT ["python", "fl.kmeans.py"]
-#ENTRYPOINT ["python", "rf.py"]
+# Keep the container running (replace with your actual command)
 CMD ["tail", "-f", "/dev/null"]
